[package]
name = "rustle-app"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.33.3"
egui = "0.33.3"
rustle-lang = { version = "0.1.0", path = "../rustle-lang" }
rustle-renderer = { version = "0.1.0", path = "../rustle-renderer" }
